// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeoQvQjKhF9L22TeBds5gXlKLkMRFQn3k',
    appId: '1:792401125583:ios:93d1f128ea27c6d1b257ba',
    messagingSenderId: '792401125583',
    projectId: 'todolist-36a93',
    storageBucket: 'todolist-36a93.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeoQvQjKhF9L22TeBds5gXlKLkMRFQn3k',
    appId: '1:792401125583:ios:93d1f128ea27c6d1b257ba',
    messagingSenderId: '792401125583',
    projectId: 'todolist-36a93',
    storageBucket: 'todolist-36a93.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV7HVYvZAW4z86t-2Bd_8vpZIVq3sylNw',
    appId: '1:792401125583:web:4854694da4f2e4aab257ba',
    messagingSenderId: '792401125583',
    projectId: 'todolist-36a93',
    authDomain: 'todolist-36a93.firebaseapp.com',
    storageBucket: 'todolist-36a93.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7HVYvZAW4z86t-2Bd_8vpZIVq3sylNw',
    appId: '1:792401125583:web:4854694da4f2e4aab257ba',
    messagingSenderId: '792401125583',
    projectId: 'todolist-36a93',
    authDomain: 'todolist-36a93.firebaseapp.com',
    storageBucket: 'todolist-36a93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyDFU97oaoYlxvHQgxK3D1pu1KUswlDgA',
    appId: '1:792401125583:android:aebbe26f588d9bb9b257ba',
    messagingSenderId: '792401125583',
    projectId: 'todolist-36a93',
    storageBucket: 'todolist-36a93.firebasestorage.app',
  );
}
